### ISSUE TITLE
Gateway timeout during upload - dataset is processed anyways

### ISSUE THREAD

**Issue by timediv** [KDD-OpenSource/fexum#109]
![image](https://cloud.githubusercontent.com/assets/5778449/23911227/6f90f69a-08dc-11e7-8b85-ebb8779d0c62.png)
![image](https://cloud.githubusercontent.com/assets/5778449/23911234/7609a3aa-08dc-11e7-922d-e7a849ef6036.png)

**Comment by nikriek** [comment]
@timediv Can I close this one?

**Comment by timediv** [comment]
never experienced it again
