### ISSUE TITLE
Only run hics once per dataset and once for all requests for specific subset in parallel

### ISSUE THREAD

**Issue by timediv** [KDD-OpenSource/fexum#128]

**Comment by nikriek** [comment]
Is that really important?

**Comment by timediv** [comment]
I was thinking this may hinder other tasks in the queue.
But if that is not the case and doesn't block the whole system in any way, I'm fine with leavin as is.

But can multiple tasks for the same target and subset actually work in parallel?

**Comment by nikriek** [comment]
jep, it's just parallel tasks. The calculation would be just waste of resources

**Comment by timediv** [comment]
But why?
Why can the results not be combined? Maybe they do actually?

**Comment by timediv** [comment]
@nikriek It's really confusing when multiple fs are running. Because which should I show to the user?
