### ISSUE TITLE
Update calculation-list endpoint

### ISSUE THREAD

**Issue by timediv** [KDD-OpenSource/fexum#149]
return
- the subset of features
- the target
- the type as enum ['default_hics', 'fixed_feature_set_hics']

**Comment by timediv** [comment]
required for https://github.com/KDD-OpenSource/fexum-frontend/issues/110

**Comment by timediv** [comment]
@JuliusKunze status?

**Comment by JuliusKunze** [comment]
@timediv Scheduled for tomorrow morning

**Comment by JuliusKunze** [comment]
Rejected idea:
Filter by use for example which we need to do for privacy reasons (Niklas' suggestion)
  - add a created_by field to the calculation model and use it as a filter

Why? This complicates sharing of cached results between users, focus is not privacy between users.
