### ISSUE TITLE
Relevancies not correctly calculated

### ISSUE THREAD

**Issue by timediv** [KDD-OpenSource/fexum#161]
mysynthetic didn't look that way previously
![image 2017-05-24 14 03 10](https://cloud.githubusercontent.com/assets/5778449/26402239/b8c435ae-4089-11e7-8342-43752d07ac97.jpg)

**Comment by nikriek** [comment]
@marcuspappik Found something out here?

**Comment by marcuspappik** [comment]
I opened a pull request with the fixed code
