### ISSUE TITLE
Add support for exclude filter

### ISSUE THREAD

**Issue by danthe96** [KDD-OpenSource/fexum#170]
See [fexum-frontend#119](https://github.com/KDD-OpenSource/fexum-frontend/pull/119). `filterParams` needs an additional string property `visibilty_exclude_filter`, nothing else.

**Comment by danthe96** [comment]
Niklas is in SFO right now, can one of you do it? It's a very quick fix, and then we can merge that PR in the frontend.

**Comment by xasetl** [comment]
it's in feature/experiment-attributes

**Comment by timediv** [comment]
Okay great :) @danthe96 can you review and integrate?

**Comment by danthe96** [comment]
@xasetl Why didn't you open a pull request? Is something not done yet?

**Comment by xasetl** [comment]
idk, it was a branch by nikriek, thought he wanted to add something.
and mainly I thought you were using this branch to test it with the frontend.

**Comment by danthe96** [comment]
Then next time either link me in the issue or open a pull request... How was I supposed to know this was done?
