### ISSUE TITLE
/calculations and /hics returns "Multiple Objects returned"

### ISSUE THREAD

**Issue by danthe96** [KDD-OpenSource/fexum#173]
[Here's the full error log](https://pastebin.com/JePxJnMr). The error is 

> MultipleObjectsReturned at *path*
get() returned more than one Relevancy -- it returned 15!

It occurs under `/api/calculations` and `/api/targets/:target-id:/hics`, whenever the user opens the analyze panel in the frontend.

The analyze window is not populated correctly and we want to take a nice screenshot for the final poster, so it should be fixed before Sunday.

**Comment by nikriek** [comment]
@marcuspappik  used to build this functionality. Maybe he has some insights
