### ISSUE TITLE
RabbitMQ error

### ISSUE THREAD

**Issue by nikriek** [KDD-OpenSource/fexum#175]
I expect it to be either a docker network issue or some mismatching dependency versions.

**Comment by timediv** [comment]
how does the problem manifest itself exactly?

**Comment by nikriek** [comment]
The tasks are not going running, because RabbitMQ loses the connection. To test it out, just upload a dataset and watch the logs

**Comment by nikriek** [comment]
Reseting docker to factory settings worked for me
